const FETCH_BALANCE = 'FETCH_BALANCE';
const FETCH_BALANCE_SUCCESS = 'FETCH_BALANCE_SUCCESS';
const FETCH_BALANCE_ERROR = 'FETCH_BALANCE_ERROR';
// 
const INCREMENT_BALANCE = 'INCREMENT_BALANCE';
const DECREMENT_BALANCE = 'DECREMENT_BALANCE';

export { FETCH_BALANCE, FETCH_BALANCE_SUCCESS, FETCH_BALANCE_ERROR, INCREMENT_BALANCE, DECREMENT_BALANCE };

